services:
  - type: web
    name: webcse340-d33m
    runtime: node
    rootDir: cse340
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false